<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchedElement</name>
   <tag></tag>
   <elementGuidId>29a03c6f-51fc-49a7-bd93-35f721721a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;search-suggest&quot;]/div/div[2]/div/div[2]/div[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;search-suggest&quot;]/div/div[2]/div/div[2]/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;search-suggest&quot;]/div/div[2]/div/div[2]/div[1]/a</value>
   </webElementProperties>
</WebElementEntity>
