<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PaginationSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9e6e74bf-4d0d-4d6e-8eb0-09c636f99b4f</testSuiteGuid>
   <testCaseLink>
      <guid>b38d93e3-cc1c-4096-8435-f6a53bade2b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Onlineshop.TestCases/ProductPage/PLP/Pagination/LastSeenPage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9e3bfd3e-c64a-408d-b00e-f1f0dc8f4b60</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PLP/GartenUndFreizeit</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9e3bfd3e-c64a-408d-b00e-f1f0dc8f4b60</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryID</value>
         <variableId>a620cfbb-2590-4a91-b327-46be1aa3e1e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e3bfd3e-c64a-408d-b00e-f1f0dc8f4b60</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category</value>
         <variableId>63d53ba2-2fa8-4ce6-865c-a4a7f6036e9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e3bfd3e-c64a-408d-b00e-f1f0dc8f4b60</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProductNr</value>
         <variableId>cb3453e8-4e48-44e4-895f-1cb5244d95fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a656568-114e-4848-b3a7-12b55fa011a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Onlineshop.TestCases/ProductPage/PLP/Pagination/ShowPagination</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d9a66cc0-214b-45d6-94e7-3a1cd4b77e7a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PLP/GartenUndFreizeit</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d9a66cc0-214b-45d6-94e7-3a1cd4b77e7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryID</value>
         <variableId>2b408bfa-1ea3-42fd-b4bc-42f0d08f5468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d9a66cc0-214b-45d6-94e7-3a1cd4b77e7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category</value>
         <variableId>c25e8ebf-fc1e-4c3e-93b9-a4ac1e6c572a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d9a66cc0-214b-45d6-94e7-3a1cd4b77e7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProductNr</value>
         <variableId>999e5f86-b9ea-462a-92db-6aa4427c7dfe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>067be077-21c1-4208-b5e7-559bf45c4b1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Onlineshop.TestCases/ProductPage/PLP/Pagination/JumpOnTheFourthBlock</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>58596b5f-56ac-4dd7-8b3e-c5f3a40c42bf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PLP/GartenUndFreizeit</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>58596b5f-56ac-4dd7-8b3e-c5f3a40c42bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryID</value>
         <variableId>27490d1c-2fb4-4cb0-8f94-54061e3dc778</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>58596b5f-56ac-4dd7-8b3e-c5f3a40c42bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category</value>
         <variableId>d26e46fd-f295-4e9c-9222-f6a96e9f5de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>58596b5f-56ac-4dd7-8b3e-c5f3a40c42bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProductNr</value>
         <variableId>2030cea5-1455-45bb-81ef-beac79ba8e8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>166ad0da-1253-4644-844d-57460dec5bec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Onlineshop.TestCases/ProductPage/PLP/Pagination/JumpOnTheThirdBlock</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8b48a19c-9c6e-4d10-8eff-645366fcd291</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PLP/GartenUndFreizeit</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8b48a19c-9c6e-4d10-8eff-645366fcd291</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryID</value>
         <variableId>2a0f2592-71b6-48e6-aa5c-1c37ccafed43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b48a19c-9c6e-4d10-8eff-645366fcd291</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category</value>
         <variableId>7306f787-b9d5-44a9-a79b-1af46f09cccb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b48a19c-9c6e-4d10-8eff-645366fcd291</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProductNr</value>
         <variableId>bba0c588-d4f7-4652-abf8-4f7675fb294f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
