<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PDPTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d26a8798-159b-4411-9140-1e38960ae355</testSuiteGuid>
   <testCaseLink>
      <guid>c1c9d97e-5302-46ae-aef6-27874ac61925</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>14c36755-0fbf-489e-ac0a-8bffb0ccc64b</id>
         <masked>false</masked>
         <name>productNo</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Onlineshop.TestCases/ProductPage/PLP/Pagination/ClickMehrProdukteAnzeigen</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dca4b484-3217-4cce-93e1-43212361f3e6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PLP/GartenUndFreizeit</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dca4b484-3217-4cce-93e1-43212361f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryID</value>
         <variableId>98790d3e-8aa4-4c7e-890a-84cb15cbcb8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dca4b484-3217-4cce-93e1-43212361f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category</value>
         <variableId>2f347166-a45c-4bc8-a7a2-9577bdf44053</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dca4b484-3217-4cce-93e1-43212361f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProductNr</value>
         <variableId>14c36755-0fbf-489e-ac0a-8bffb0ccc64b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
