<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShowMoreProductsButton</name>
   <tag></tag>
   <elementGuidId>743c916a-b84f-486f-a8cc-bf67ceb83fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'main/section/div/button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-message=&quot;adb-show-more-products-button&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div#main>section>div>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-secondary</value>
      <webElementGuid>f3704f8f-dc67-4382-8c6c-bc0c0ee84404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main/section/div/button</value>
      <webElementGuid>cc8973c8-17b3-488a-8d37-037e419a64c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
