<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShowMoreProductsButton</name>
   <tag></tag>
   <elementGuidId>743c916a-b84f-486f-a8cc-bf67ceb83fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'main/section/div/button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>xpath=//div[@id='main']/section/div/button</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div#main>section>div>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-secondary</value>
      <webElementGuid>dbd7ebf2-e4d8-4bb6-a8ae-68646a539c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main/section/div/button</value>
      <webElementGuid>17fa3406-80f5-466d-bfb8-4f587efcefb7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
