<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaterialButton</name>
   <tag></tag>
   <elementGuidId>56ee88d0-9a1d-42f0-9cfb-e287d4b6363a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-collapse-target='navigation-facet-card-body-Material00000967']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-collapse-target='navigation-facet-card-body-Material00000967']</value>
      <webElementGuid>6dc37298-14a0-41b0-a045-df24440cdcc2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
