<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OffersButton</name>
   <tag></tag>
   <elementGuidId>18fee6b7-a58b-4fac-bc7e-9ac6a7bdf959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-collapse-target='navigation-facet-card-body-offer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-collapse-target='navigation-facet-card-body-offer']</value>
      <webElementGuid>ab8a0e0d-d701-45db-aded-e223405b4c11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
