<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductImage</name>
   <tag></tag>
   <elementGuidId>32cad9ef-cf14-48f8-8651-2b385a1694a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='https://media.bahag.cloud/m/746470/15.jpg']</value>
      <webElementGuid>89831e27-20d1-4093-8c7e-8f392e16942c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
