<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonOnlineReservation</name>
   <tag></tag>
   <elementGuidId>0ef1ada8-b426-470c-8f9b-5aaeb3911912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='submitButtonReserve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='submitButtonReserve']</value>
      <webElementGuid>e709c449-b068-4a28-be2f-8d24363f37d9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
