<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductImage</name>
   <tag></tag>
   <elementGuidId>32cad9ef-cf14-48f8-8651-2b385a1694a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='product-list-tile__image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='https://media.bahag.cloud/m/746470/15.jpg']</value>
      <webElementGuid>3f034c95-071b-4411-a95c-181eddeb65e8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
