<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelNumberOfProducts</name>
   <tag></tag>
   <elementGuidId>08ba0cab-1643-43fb-aa75-cc2c36fe5993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>html>body>main>div:nth-of-type(3)>div>div>h1>span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='page-title__addition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='page-title__addition']</value>
      <webElementGuid>79e56c38-fcf0-4f70-bf99-43d0fe693ea8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
